### ISSUE TITLE
Unable to install (getting requirements to build wheel... error)

### ISSUE THREAD

**Issue by aibradford** [ageorge/beets-bandcamp#16]
I'm receiving this errorwhen trying to install:

```
Collecting beets-bandcamp
  Using cached beets-bandcamp-0.1.4.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in beets-bandcamp setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected
end or semicolon (after version specifier)
          six>=1.9requests
             ~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip


```

Can anyone tell me what im doing wrong?

**Comment by unrblt** [comment]
Hi! I haven't used this in a while. Maybe you should try this fork instead: 

https://github.com/snejus/beetcamp

I haven't tried it personally but seems well maintained and has a lot more functionality than this one.

**Comment by JOJ0** [comment]
> Hi! I haven't used this in a while. Maybe you should try this fork instead: 
> 
> 
> 
> https://github.com/snejus/beetcamp
> 
> 
> 
> I haven't tried it personally but seems well maintained and has a lot more functionality than this one.

Yes snejus fork is very well maintained and definitely working!
