### ISSUE TITLE
Enter release ID/URL

### ISSUE THREAD

**Issue by bonyboy** [ageorge/beets-bandcamp#2]
Is it possible to incorporate some ability to paste in a direct id/url when the results come back negative similar to what you can do with Musicbrainz or Discogs ID?

**Comment by 0x1f415** [comment]
this is already possible, I do it regularly. just paste an album url like `https://wolfgun.bandcamp.com/album/road-to-jupiter`

**Comment by unrblt** [comment]
As @0x1f415 says, the full bandcamp url is the id. This works for both albums and songs.
