### ISSUE TITLE
Tagging of compilation albums

### ISSUE THREAD

**Issue by gryphonmyers** [ageorge/beets-bandcamp#3]
I've noticed a pattern of some releases getting tagged with artists named in their track titles, and the awful "various artists" or name of record label for the artist tag. Here's an example:

https://schematicmusiccompany.bandcamp.com/album/still-ill

and another:

http://store.origamisound.com/album/borealis-voidness-remixed

It's pretty clear why this is happening, and I'm not sure there is a way around it, since it seems like the artist names are getting baked into the track title markup. I haven't studied the markup closely enough, nor have I used Bandcamp enough to know if the record labels are baking the artist names in themselves, or if Bandcamp is doing it. If there is a pattern, we could probably account for it and split on ' - ', but then of course you run the risk of a false positive.  

I have more examples, if that is any help.

**Comment by unrblt** [comment]
I've added a new option [`split_artist_title`](https://github.com/unrblt/beets-bandcamp/blob/develop/README.rst) in [develop](https://github.com/unrblt/beets-bandcamp/tree/develop) to enable the splitting you suggested. I think it's very fragile and can give a lot of false positives so it is disabled by default.

What I used to do was use [edit](https://beets.readthedocs.io/en/latest/plugins/edit.html)'s plugin interactive options to edit the tags before saving them. You may still need to do that sometimes but I think it's easier with the splitting enabled.

**Comment by unrblt** [comment]
I've just released the `0.1.3` version with the new option.
